# Super simple makefile

all: clean build run

build:
	@echo "Compiling..."
	@g++ -std=c++11 ordena.cpp -o ordena.o 
	
run:
	@echo "Running build..."
	@./ordena.o

clean:
	@echo "Cleaning files..."
	@rm -f ./ordena.o
